#!/usr/bin/env php
<?php
include __DIR__ . '/../autoload.php';
use Wukka\Test as T;
use Wukka\Store;

$plan_ct = 1;

$cache = new Store\Gate(new Store\EmbeddedTTL(new \Wukka\Store));
include __DIR__ . '/generic_tests.php';


$cache = new Store\Gate(new Store\EmbeddedTTL(new \Wukka\Store));
$cache->set('test1', 1, 10000000);

$noerrs = TRUE;
set_error_handler( function ( $errno, $errstr) use( & $noerrs ) { $noerrs = FALSE; } );
$v = $cache->get('test1');
restore_error_handler();

// need to run on 32 bit os to verify
T::ok( $noerrs, 'no warnings generated by huge number blowup in mt_rand');
